hash-format = "sha256"

[[files]]
file = "config/figura.json"
hash = "a91614a74aed378b44ab40a1820b91b33ed445e203b44ab4b16e6276711bdfb3"

[[files]]
file = "mods/additional-placements-fabric.pw.toml"
hash = "f91467703d4b5f18a31dbc5c03b1a73a44521b61de6d8a0772d30b989f5bcc0c"
metafile = true

[[files]]
file = "mods/advanced-networking.pw.toml"
hash = "6745ecd51c4117e6f836c238721b669c80f4c3ea4eb0ed5f2bdfc378595bc375"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "9caa254bdbb9dbafd1cc29616cd6aa26f4972eb583961225cf8a8b4836071bfb"
metafile = true

[[files]]
file = "mods/armor-poser.pw.toml"
hash = "6c1718dabfb7bc27f768400f2cff9b5ed77f084171aab57bb5ac819e5e0398d7"
metafile = true

[[files]]
file = "mods/cardinal-components-api.pw.toml"
hash = "b7cd611b5e509f9f8d5e5db356781f4921a33d908ca9fe8eb20b8c1bbc526515"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "931fa7587facbc9b334c7539722b2dacaac520f253ebfbc5b87665d5abbcea77"
metafile = true

[[files]]
file = "mods/connected-doors.pw.toml"
hash = "0e335932a555bc6cfa77854f76e833125097698ebf8ebdb3625be8ddaca2f8c7"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "dded3880e723049a3d26ce915edf37ea1a86b4e45fc8fa47a9ec96b85596f36e"
metafile = true

[[files]]
file = "mods/delightful-froge.pw.toml"
hash = "6a5b425f56d3bc3772ccb987bace4b2b088bd1330a29deeb9be6e67089ed072b"
metafile = true

[[files]]
file = "mods/e4mc.pw.toml"
hash = "b0a96ca2358570d64d7e0f8d6c65ca140034aee3f5296beffc5001fa52308631"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "8435fe34f180c963234295c6bf8de293b3450d74f2ab74389ac9bdf198d84612"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "61afd7af5c645ffd966b2bd86be944eacd1e48a8044e8f67082225d4d9989f0c"
metafile = true

[[files]]
file = "mods/fancy-door-animations.pw.toml"
hash = "5b4cf43a762ac3899f62827c529834a00824d591b4800e1d7c52a855b34499a7"
metafile = true

[[files]]
file = "mods/fdmc-0.2.4mc1.20.4.jar.disabled"
hash = "66cd008810d248910d7c9d7da0f48faafbaba9f88bbfac6b5cb040c03c116927"

[[files]]
file = "mods/figura.pw.toml"
hash = "3536324851331d802192df60473aa6818c3f5a332dd58b579a3da5813ff43430"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "9dc337ffb127f1b1f24c57f8c3fc739e21b2139050d41baf55357fad8b42c83b"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "83ad7d21bc43be38232b2d818ac5b9d45a44a03c140709eb3e0aa26ea73dca37"
metafile = true

[[files]]
file = "mods/gravity-api-fork.pw.toml"
hash = "5f8ebc1a54f64a6e88ab944f962b6838e7e1a1d9f77ed27851def53077a7bb2b"
metafile = true

[[files]]
file = "mods/hyperleash.pw.toml"
hash = "7e440aceae16f98d22d99516f44102b80b5e728d35c6836be0f35e60b839f60b"
metafile = true

[[files]]
file = "mods/immersiveportals.pw.toml"
hash = "b5e8b41a632a7a383d5dd0a0141c0a4579f73f4a787ec63a5f9cf719f39537cd"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "db812a9b3a4a8ea011eedc44bdc4df13a1f3cfb67130fe57d3990342566d03a8"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "57fc1c61ba53059ccb27647cf44d4b8671ccf284fcd869ec1b6c04a94eb8335e"
metafile = true

[[files]]
file = "mods/miniscaled.pw.toml"
hash = "c6630ff951c43aaf03dfd592f524f8fae409058a7111eaccbb150927945f9ba8"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "07114208e332aa5fbc3e7144c2bac58ea74e50d4eaeac2b6c6cc5c41286bb335"
metafile = true

[[files]]
file = "mods/nodeflow.pw.toml"
hash = "6cb9df2db76cac63a0145b5ce4be9328e66ab9922809629a9e84b4c09df39a0c"
metafile = true

[[files]]
file = "mods/ok-boomer.pw.toml"
hash = "4bb4cc0536883fa919fc0b73cc8c233cd250f2b02d58091db44a0ab96c08211b"
metafile = true

[[files]]
file = "mods/oooze.pw.toml"
hash = "59d780b4e652d8b5b352e014dd07fb94983384c48ec7e4e3ebbfb86de0e73a87"
metafile = true

[[files]]
file = "mods/orbital-railgun-enhanced.pw.toml"
hash = "5c9e20438e1ab112bb0bdd4444525a8fc43e60b5680ecec11bf7ef80b420a78b"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "499255558fba5abfa0760fe875fd624d5543cf7b8915651ea7f389fa5897b1ad"
metafile = true

[[files]]
file = "mods/patpat.pw.toml"
hash = "dce2382208b555aa2952c15ada3ba49203c1e420319fa1c678ac8a5f6d35fff6"
metafile = true

[[files]]
file = "mods/pehkui.pw.toml"
hash = "43b4a9ca9aaac5a16ed067aee92cafaf30d6166d62d7fa851179c6257ed75b59"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "de46918876de129bf08aa27420ec9b99b373dbccac7acaebd82e46b4c28836b5"
metafile = true

[[files]]
file = "mods/portable-hole.pw.toml"
hash = "ab23164c6851c8042b6507a1696ca4cb2b7aa33dda1ebe036032b1734201b6e0"
metafile = true

[[files]]
file = "mods/portal-gun.pw.toml"
hash = "872c2a2b3803fbe9c414cf06616362e14d728ea35d0955c76c4e549df978a4ad"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "526b8f53a36dcae5e94a6a9e90a4caf7a80a43c08fe79f3344a582b2bfb800e3"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "1ee2fbdd79b37133dbd6c0f0dcf285e5d7c4a4d6720b4f1ac001144f74da3023"
metafile = true

[[files]]
file = "mods/satin-api.pw.toml"
hash = "87d5fa07006ab150ebaa81c7f776ae367670a78a2c54740c46a0ced3a9a13f0c"
metafile = true

[[files]]
file = "mods/seamless.pw.toml"
hash = "da97bbfeded4bafab4fe7917796370f6fe2e5d69bc93f861bd7e52206bd92e3c"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "521c8241593053f877a89ce447c64392c3619e16c2001b3cac7d72cbde8392d0"
metafile = true

[[files]]
file = "mods/wearthat.pw.toml"
hash = "57af14d4b92dc7db3065a0c4f292d48cc6b6e57ae2816675c4e82475b6af8388"
metafile = true

[[files]]
file = "mods/webstreamer.pw.toml"
hash = "978cc314d07347dc2bcd23e56f93992d79ee5b89a3947d74221b758e8f685e17"
metafile = true

[[files]]
file = "mods/wheelchairs.pw.toml"
hash = "d73a5cd062804b42fead295236fba0f4c3e2ab3b7eb1ecd78fcaea93bda834a3"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "8a7bab663c386b0e31a5730d4c585baae859ea47ff716fa30fd8d0103ccba1a4"
metafile = true
