name = "Cringe Portals"
author = "chyzman"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "311eaf24d7ace0f7811a923808bcb3432bad1e06be4f431fa448a927831e65bd"

[versions]
fabric = "0.18.4"
minecraft = "1.20.4"
