name = "Cringe Portals"
author = "chyzman"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc0e4ec8d333e30ddc77a59fcf099afa76dfbc83e52f9321d1b87f6b4bb6d585"

[versions]
fabric = "0.18.4"
minecraft = "1.20.4"
