name = "Cringe Portals"
author = "chyzman"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "108b5bb682beb93a21d74a260975639ab6088490893abf0881c63f5b053b28db"

[versions]
fabric = "0.18.4"
minecraft = "1.20.4"
