name = "Cringe Portals"
author = "chyzman"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1aefa5bf27a1a3b1b97e2245002ac4adc8c057813324fd3ab780060582f7f5b9"

[versions]
fabric = "0.18.4"
minecraft = "1.20.4"
